[project]
name = "ex1001"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yujins01", email = "neosyj01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.12",
]

[project.scripts]
ex1001 = "ex1001:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
