[project]
name = "ch07"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yujins01", email = "neosyj01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
ch07 = "ch07:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
